-- 99. Count the total number of employees in the company.
select count(*) from employees

-- 100. Count how many employees work in each department.
select department_id, count(*) as count_employees from employees
group by department_id

-- 101. Find the average salary across all employees.
select AVG(salary) from employees


-- 102. Find the average salary per department.
select department_id, AVG(salary) as average_salary from employees
group by department_id

-- 103. Find the highest and lowest salary in the company in a single query.
select min(salary) as min, max(salary) as max from employees


-- 104. Find the total value of all products currently in stock (price multiplied by stock quantity, summed).
select SUM(price * stock_quantity) as total_products_value from products

-- 105. Count how many orders each customer has placed.
select customer_id, count(*) as count_orders from orders
group by customer_id

-- 106. Find the total revenue generated by each product (sum of quantity multiplied by unit price from order_items), grouped by product.
select product_id, SUM(quantity * unit_price) as total_revenue
from order_items
group by product_id

-- 107. Find the number of products in each category, but only show categories that have more than 2 products (use HAVING).
select category, COUNT(*) as product_count from products
group by category
having COUNT(*) > 2

-- 108. Find departments where the average employee salary is above 6000 (use HAVING).
select department_id, AVG(salary) as average_salary from employees
group by department_id
having AVG(salary) > 6000

-- 109. Find the total number of orders placed for each order status.
select status, COUNT(*) as order_count
from orders
group by status

-- 110. Find the earliest and latest hire date in the employees table
select MIN(hire_date) as earliest, MAX(hire_date) as latest
from employees



